import {useState} from 'react';
import {ArrowUpRight,ArrowRight,ArrowDownRight,Sun,Moon,Footprints,Utensils,Wind,Scale,Heart,Plus,Sparkles,FlaskConical,Leaf,Watch} from 'lucide-react';
import {AreaChart,Area,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {toast} from 'sonner';
import {api} from './api';
import {Link,Chips} from './shared';
import {latest,format,providers,dateLabel,type State,type ViewProps} from './types';
const icons:any={moon:Moon,scale:Scale,food:Utensils,watch:Watch,wind:Wind};
export default function Dashboard({s,refresh,openMeal}:ViewProps&{openMeal:()=>void}){
 const [range,setRange]=useState(7),[busy,setBusy]=useState(false);const v=(k:string)=>latest(s,k),f=(k:string,d=0)=>format(v(k),d);
 const simulate=async()=>{setBusy(true);try{const r=await api('ingest/simulate',{});await refresh();toast.success(r.message)}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
 const sleep=v('sleep_hours'),active=v('active_kcal'),p=s.profile;const score=sleep!==null&&active!==null?Math.round(Math.min(100,sleep/8*100)*.5+Math.min(100,active/p.move_goal*100)*.5):null;
 const weight=s.metrics.filter(m=>m.type==='weight_kg');const delta=weight.length>1?weight.at(-1)!.value-weight[0].value:null;const total=(key:string)=>s.meals.reduce((n,m)=>n+m[key],0);
 return <><div className="page-heading"><div><p className="eyebrow">A NEW DAY. A LITTLE PROGRESS.</p><h1>Your daily check-in <span className="heading-sun"><Sun size={31}/></span></h1><p>All the little things that make you, you.</p></div><button className="button secondary simulate" onClick={simulate} disabled={busy} title="Simulate new data" aria-label="Simulate new data"><FlaskConical size={16}/><span>{busy?'Checking in…':'Simulate new data'}</span></button></div>
 <div className="welcome-row"><section className="welcome-card stamp"><div className="welcome-copy"><div className="handwritten hello">Hey {p.name}, I’m {p.twin_name}! <span>♡</span></div><h2>{sleep!==null&&sleep<6?'Let’s take it gently today.':'You’re growing good habits.'}</h2><p>A good night’s sleep, a little movement, and one nourishing meal at a time. You’ve got this.</p><Link href="/twin" className="button primary">Let’s check in <ArrowUpRight size={18}/></Link></div><img className="welcome-art" src="/art/garden.png" alt="A cheerful avocado walking through a sunny watercolor garden"/></section><section className="score-card stamp"><span className="eyebrow">TODAY’S BALANCE</span><div className="score-dial"><svg viewBox="0 0 120 120" aria-hidden="true"><circle className="ring-base" cx="60" cy="60" r="49"/><circle className="ring-fill" cx="60" cy="60" r="49" strokeDasharray={`${(score??0)*3.08} 308`}/></svg><div><b>{score??'—'}</b><span>/ 100</span></div></div><span className="score-state"><Leaf size={14}/>{score===null?'A fresh start':'Growing steadily'}</span><p>Illustrative sleep + activity score.<br/>Not a medical assessment.</p></section></div>
 <div className="section-heading"><h2>Your health, in little pieces <span className="handwritten">all connected.</span></h2><div className="range-tabs" role="group" aria-label="Chart date range">{[7,30].map(n=><button key={n} className={range===n?'active':''} aria-pressed={range===n} onClick={()=>setRange(n)}>{n} days</button>)}</div></div>
 <div className="dashboard-layout"><div className="metric-grid">
 <Metric s={s} id="oura" title="Sleep" num="01" icon={Moon} color="blue"><div className="metric-value">{sleep===null?'—':<>{Math.floor(sleep)}<small>h</small>{Math.round(sleep%1*60)}<small>m</small></>}<span className="metric-tag">{sleep===null?'No duration yet':sleep>=7?'Rested & ready':'A gentler day'}</span></div><p className="metric-caption">A little time to recharge</p><SparkChart s={s} type="sleep_hours" range={range} color="#7596b0"/><div className="metric-bottom"><span>Sleep score <b>{f('sleep_score')}</b></span><span>HRV <b>{f('hrv')} ms</b></span></div></Metric>
 <Metric s={s} id="renpho_scale" title="Body" num="02" icon={Scale} color="peach"><div className="metric-value">{f('weight_kg',1)}<small>kg</small>{delta!==null&&<span className="trend"><ArrowDownRight size={14}/>{format(delta,1)} kg / trend</span>}</div><p className="metric-caption">One piece of your bigger picture</p><SparkChart s={s} type="weight_kg" range={range} color="#bd8969"/><div className="metric-bottom"><span>Body fat <b>{f('body_fat_pct',1)}%</b></span><span>Muscle <b>{f('muscle_kg',1)} kg</b></span></div></Metric>
 <Metric s={s} id="renpho_food" title="Nutrition" num="03" icon={Utensils} color="yellow"><div className="metric-value">{format(total('kcal'))}<small>kcal</small><button className="icon-button" aria-label="Log a meal" onClick={openMeal}><Plus size={18}/></button></div><p className="metric-caption">of {format(p.calorie_goal)} kcal · little bites add up</p><div className="macro-bars">{[['Protein','protein_g',p.protein_goal],['Carbs','carbs_g',240],['Fat','fat_g',70]].map(([name,key,goal]:any)=><div key={key}><span>{name}</span><div className="progress" role="progressbar" aria-label={name} aria-valuenow={Math.min(100,total(key)/goal*100)} aria-valuemin={0} aria-valuemax={100}><span style={{width:Math.min(100,total(key)/goal*100)+'%'}}/></div><b>{format(total(key))}g</b></div>)}</div><button className="text-button card-action" onClick={openMeal}>{s.meals.length} meals in your journal <ArrowRight size={14}/></button></Metric>
 <Metric s={s} id="apple_watch" title="Movement" num="04" icon={Footprints} color="green"><div className="movement-main"><div><div className="metric-value">{f('steps')}</div><p className="metric-caption">steps & a little fresh air</p><span className="movement-note">Every step counts.</span></div><div className="activity-rings"><svg viewBox="0 0 100 100" role="img" aria-label={`Active calories ${f('active_kcal')}, exercise minutes ${f('exercise_min')}, stand hours ${f('stand_hours')}`}>{[[41,'#c78269',(v('active_kcal')??0)/p.move_goal],[30,'#899b61',(v('exercise_min')??0)/30],[19,'#83a7b0',(v('stand_hours')??0)/12]].map(([r,c,fraction]:any)=><g key={r}><circle cx="50" cy="50" r={r} fill="none" stroke={c} strokeWidth="8" opacity=".2"/><circle cx="50" cy="50" r={r} fill="none" stroke={c} strokeWidth="8" strokeLinecap="round" strokeDasharray={`${Math.min(1,fraction)*2*Math.PI*r} 500`} transform="rotate(-90 50 50)"/></g>)}</svg></div></div><div className="metric-bottom"><span>Move <b>{f('active_kcal')}/{p.move_goal} kcal</b></span><span>Exercise <b>{f('exercise_min')} min</b></span></div></Metric>
 <Metric s={s} id="lumen" title="Metabolism" num="05" icon={Wind} color="purple"><div className="metric-value">Level {f('lumen_level')}<small>/ 5</small><span className="metric-tag">{v('lumen_level')===null?'No reading':v('lumen_level')!<=2?'More fat burn':'More carb burn'}</span></div><p className="metric-caption">Your latest breath check-in</p><div className="lumen-scale">{[1,2,3,4,5].map(n=><span key={n} className={n===v('lumen_level')?'selected':''}>{n}</span>)}</div><div className="scale-labels"><span>Fat burn</span><span>Carb burn</span></div><div className="metric-bottom"><span>Weekly flex score</span><b>{f('flex_score',1)}</b></div></Metric>
 <section className="focus-card stamp"><div className="metric-head"><span className="stamp-number">06</span><Heart size={18}/><h3>One little focus</h3></div><div className="focus-star">✧</div><h3>Make room for<br/>a nourishing dinner.</h3><p>A protein source, colorful veggies,<br/>and a moment to slow down.</p><Link href="/twin?prompt=What%20should%20I%20focus%20on%20for%20dinner%3F" className="text-button">Make a little plan <ArrowRight size={15}/></Link></section>
 </div><aside className="insights-panel"><div className="insights-title"><Sparkles size={20}/><h2>A note from {p.twin_name}</h2></div><p className="handwritten insights-subtitle">Connecting the little dots…</p>{s.insights.map((x,i)=><article className="insight" key={x.id}><span className={`insight-number ${x.color}`}>{String(i+1).padStart(2,'0')}</span><h3>{x.title}</h3><p>{x.text}</p><Chips sources={x.sources}/><Link href={'/twin?prompt='+encodeURIComponent(x.prompt)} className="text-button">Ask my twin <ArrowUpRight size={15}/></Link></article>)}{!s.insights.length&&<p className="empty-message">Connect a source and allow your twin to read it to begin finding patterns.</p>}<div className="insights-foot"><Heart size={16}/><span>Here to help you understand,<br/>one small piece at a time.</span></div></aside></div>
 <div className="connections-strip"><span><span className="connected-dot"/>{s.connections.filter(c=>c.status==='connected').length} companions, one picture.</span><div>{providers.map(p=>{const Icon=icons[p.icon],c=s.connections.find(c=>c.provider===p.id);return <Link href="/settings" key={p.id} className={c?.status==='connected'?'':'disconnected'}><Icon size={15}/>{p.short} · {c?.mode}</Link>})}</div><Link className="text-button" href="/settings">Manage <ArrowUpRight size={14}/></Link></div></>
}
function Metric({s,id,title,num,color,icon:Icon,children}:any){const c=s.connections.find(c=>c.provider===id),has=id==='renpho_food'||s.metrics.some(m=>m.source===id);return <section className={`metric-card stamp ${color}`}><div className="metric-head"><span className="stamp-number">{num}</span><Icon size={19}/><h3>{title}</h3><span className="source-label">{providers.find(p=>p.id===id)?.short}<small className="source-mode">{c?.mode}</small></span></div>{c?.status==='connected'&&has?children:<div className="empty-metric"><Icon size={28}/><p>{c?.status==='connected'?'Waiting for your first reading.':'A little connection makes a bigger picture.'}</p><Link href="/settings" className="text-button">Manage source <ArrowRight size={14}/></Link></div>}</section>}
function SparkChart({s,type,range,color}:any){const cutoff=Date.now()-range*86400000;const rows=s.metrics.filter(m=>m.type===type&&Date.parse(m.timestamp)>=cutoff).map(m=>({value:m.value,date:dateLabel(m.timestamp)}));return <div className="spark-chart">{rows.length?<><ResponsiveContainer width="100%" height={70}><AreaChart data={rows} margin={{top:8,right:4,left:4,bottom:0}}><defs><linearGradient id={'g-'+type} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={.25}/><stop offset="100%" stopColor={color} stopOpacity={0}/></linearGradient></defs><XAxis dataKey="date" hide/><YAxis hide domain={['dataMin - 0.5','dataMax + 0.5']}/><Tooltip contentStyle={{fontSize:13,border:'1px solid #d2c9b8',borderRadius:6,background:'#fffcf4'}} formatter={v=>[v,type==='sleep_hours'?'Hours':'Weight (kg)']}/><Area type="monotone" dataKey="value" stroke={color} strokeWidth={2} fill={'url(#g-'+type+')'} isAnimationActive={false}/></AreaChart></ResponsiveContainer><div className="chart-dates"><span>{rows[0]?.date}</span><span>{rows.at(-1)?.date}</span></div></>:<p className="empty-chart">No readings in this date range.</p>}</div>}
