import {useEffect,useState} from 'react';
import {Plus,Check,Upload,Pencil,ArrowRight} from 'lucide-react';
import {toast} from 'sonner';
import {api,uploadReport} from './api';
import {Modal,Field,navigate} from './shared';
import type {ViewProps} from './types';
type Props=ViewProps&{open:boolean;onClose:()=>void};
const emptyMeal={food_name:'',meal:'breakfast',grams:200,kcal:180,protein_g:20,carbs_g:20,fat_g:4};
export function MealDialog({open,onClose,s,refresh}:Props){
 const [meal,setMeal]=useState<any>(emptyMeal),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open){setMeal({...emptyMeal});setError('')}},[open]);
 const save=async()=>{setBusy(true);setError('');try{await api('food-log',meal);await refresh();onClose();toast.success('A little nourishment, logged.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <Modal open={open} onClose={()=>{if(!busy)onClose()}} title="A little nourishment." description="Add a meal using the nutrition values from its label." wide><div className="meal-history">{s.meals.map(m=><div key={m.id}><span>{m.food_name}<small>{m.meal} · {m.grams}g</small></span><b>{m.kcal} kcal<small>{m.protein_g}g protein</small></b></div>)}{!s.meals.length&&<p>No meals logged today yet.</p>}</div>{error&&<div className="modal-error" role="alert">{error}</div>}<form onSubmit={e=>{e.preventDefault();save()}}><div className="form-grid"><Field label="Food or meal" value={meal.food_name} onChange={e=>setMeal({...meal,food_name:e.target.value})} required maxLength={200} placeholder="e.g. Greek yogurt & berries"/><label className="field"><span>Meal</span><select value={meal.meal} onChange={e=>setMeal({...meal,meal:e.target.value})}>{['breakfast','lunch','dinner','snack'].map(n=><option key={n} value={n}>{n.charAt(0).toUpperCase()+n.slice(1)}</option>)}</select></label>{[['Portion (grams)','grams',3000],['Calories (kcal)','kcal',5000],['Protein (g)','protein_g',300],['Carbs (g)','carbs_g',500],['Fat (g)','fat_g',300]].map(([label,k,max]:any)=><Field key={k} label={label} type="number" value={meal[k]} min={0} max={max} step="0.1" required onChange={e=>setMeal({...meal,[k]:Number(e.target.value)})}/>)}</div><div className="form-footer"><button className="text-button" type="button" onClick={()=>setMeal({food_name:'Greek yogurt & blueberries',meal:'breakfast',grams:250,kcal:215,protein_g:24,carbs_g:27,fat_g:2})}>Use sample breakfast values</button><button className="button primary" type="submit" disabled={busy}>{busy?'Saving…':'Add to my journal'}<Plus size={16}/></button></div></form></Modal>
}
const fields:[string,string,string,number?,number?][]=[['test_date','Test date','date'],['weight_kg','Weight (kg)','number',20,400],['body_fat_pct','Body fat (%)','number',1,80],['muscle_kg','Muscle mass (kg)','number',1,200],['visceral_fat','Visceral fat index','number',0,100],['bmr_kcal','BMR (kcal)','number',500,5000],['body_score','Body score / 100','number',0,100],['bmi','BMI','number',5,100],['skeletal_muscle_kg','Skeletal muscle (kg)','number',0,200],['body_water_kg','Body water (kg)','number',0,300],['bone_kg','Bone mass (kg)','number',0,20],['protein_kg','Protein mass (kg)','number',0,100],['subcutaneous_fat_pct','Subcutaneous fat (%)','number',0,80],['metabolic_age','Metabolic age','number',1,120],['whr','Waist-to-hip ratio','number',0,3]];
export function ReportDialog({open,onClose,s,refresh}:Props){
 const [stage,setStage]=useState('choose'),[data,setData]=useState<any>({}),[confidence,setConfidence]=useState<any>({}),[mode,setMode]=useState('manual'),[upload,setUpload]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reviewed,setReviewed]=useState(false);
 useEffect(()=>{if(open){setStage('choose');setData({test_date:s.serverDate});setUpload(null);setError('');setReviewed(false);setConfidence({});setMode('manual')}},[open]);
 const read=async(file:File)=>{if(!file)return;if(!['image/png','image/jpeg','application/pdf'].includes(file.type)||file.size>10*1024*1024){setError('Choose a JPG, PNG, or PDF smaller than 10 MB.');return}setBusy(true);setError('');try{const result=await uploadReport(file);setData({test_date:s.serverDate,...result.fields});setConfidence(result.confidence);setMode(result.mode);setUpload({id:result.upload_id,mime:file.type,name:file.name});setMessage(result.message);setStage('review')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const sample=async()=>{setBusy(true);try{const r=await api('reports/sample');setData(r.fields);setConfidence(r.confidence);setMode('sample');setUpload(null);setMessage('These numbers are sample data, not readings from an uploaded file.');setStage('review')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const confirm=async()=>{setBusy(true);setError('');try{const normalized={...data};for(const [k,,type] of fields){if(type==='number'){if(normalized[k]===''||normalized[k]===undefined||normalized[k]===null)delete normalized[k];else normalized[k]=Number(normalized[k])}}await api('reports/renpho/confirm',{fields:normalized,mode,reviewed:true,upload_id:upload?.id??null});await refresh();onClose();navigate('/twin');toast.success('Your report is saved and your twin has a new journal note.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <Modal open={open} onClose={()=>{if(!busy)onClose()}} title={stage==='choose'?'A new page in your body story.':'Let’s check the little details.'} description={stage==='choose'?'Upload a RENPHO image or PDF, then review the measurements.':mode==='sample'?'Sample report · please review the values.':upload?.name||'Manual entry · add the values you can verify.'} wide={stage==='review'}>
 {error&&<div className="modal-error" role="alert">{error}</div>}
 {stage==='choose'?<><label className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)read(e.dataTransfer.files[0])}}><Upload size={32}/><b>{busy?'Reading your report…':'Drop your RENPHO report here'}</b><span>or choose a JPG, PNG, or PDF · up to 10 MB</span><input type="file" accept="image/jpeg,image/png,application/pdf" aria-label="Choose RENPHO report" disabled={busy} onChange={e=>{if(e.target.files?.[0])read(e.target.files[0])}}/></label><p className="form-note">{s.aiEnabled?'Your report will be sent from the Python backend to Claude for extraction. You review every value before it is saved as health data.':'Your file stays on the Python server. Automatic extraction needs an AI connection; manual review and sample reports work now.'}</p><div className="dialog-actions"><button className="button secondary" disabled={busy} onClick={()=>{setStage('review');setMode('manual');setMessage('Enter the numbers from your report. Nothing is filled in automatically.')}}>Enter values manually</button><button className="button primary" disabled={busy} onClick={sample}>Try the sample report <ArrowRight size={16}/></button></div></>:
 <>{upload?.mime.startsWith('image/')&&<img className="report-preview" src={'/api/reports/files/'+upload.id} alt="Your uploaded body report"/>}{upload?.mime==='application/pdf'&&<iframe className="report-preview-frame" src={'/api/reports/files/'+upload.id} title="Uploaded body report PDF"/>}<div className="review-note"><Pencil size={17}/>{message}</div><form onSubmit={e=>{e.preventDefault();confirm()}}><div className="form-grid report-fields">{fields.map(([k,label,type,min,max],index)=><label className="field" key={k}><span>{label}{index<6?' *':''}{confidence[k]!==undefined&&confidence[k]<.8?' · please check':''}</span><input className={mode!=='sample'&&(confidence[k]===undefined||confidence[k]<.8)?'needs-review':''} type={type} value={data[k]??''} min={min} max={max} step={type==='number'?'0.01':undefined} required={index<6} onChange={e=>setData({...data,[k]:e.target.value})}/></label>)}</div><details className="report-details"><summary>Other report fields</summary><p>Segmental values, device evaluations, and impedance are retained with the full report.</p><pre className="bridge-code">{JSON.stringify(Object.fromEntries(Object.entries(data).filter(([key])=>!fields.some(f=>f[0]===key))),null,2)}</pre></details>{mode==='sample'&&<p className="form-note">The sample device’s “optimal weight” and suggested weight change use different targets. This app does not convert them into a weight-loss prescription.</p>}<label className="check-label"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)} required/>I reviewed these values and understand they are device estimates.</label><div className="form-footer"><button type="button" className="text-button" disabled={busy} onClick={()=>setStage('choose')}>Back</button><button type="submit" className="button primary" disabled={busy||!reviewed}>{busy?'Saving…':'Confirm & add to journal'}<Check size={16}/></button></div></form></>}
 </Modal>
}
