import {useEffect,useRef,useId,type ReactNode,type AnchorHTMLAttributes} from 'react';
import {X,AlertTriangle} from 'lucide-react';
export function navigate(path:string){window.history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo(0,0);}
export function Link({href,children,onClick,...props}:AnchorHTMLAttributes<HTMLAnchorElement>){return <a href={href} {...props} onClick={event=>{onClick?.(event);if(!event.defaultPrevented&&href?.startsWith('/')&&!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&event.button===0){event.preventDefault();navigate(href);}}}>{children}</a>}
export function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null),last=useRef<HTMLElement|null>(null),id=useId();
 useEffect(()=>{const d=ref.current;if(open&&!d?.open){last.current=document.activeElement as HTMLElement;d?.showModal();}else if(!open&&d?.open){d.close();last.current?.focus();}},[open]);
 return <dialog ref={ref} className={wide?'wide':''} aria-labelledby={id+"-title"} aria-describedby={description?id+"-description":undefined} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===ref.current){const r=ref.current!.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose()}}}><button className="dialog-close" onClick={onClose} aria-label="Close dialog"><X size={21}/></button><div className="dialog-heading"><p className="eyebrow">YOUR HEALTH JOURNAL</p><h2 id={id+"-title"}>{title}</h2>{description&&<p id={id+"-description"}>{description}</p>}</div>{children}</dialog>
}
export function Field({label,name,value,onChange,type='text',required=false,min,max,step,maxLength,placeholder}:any){return <label className="field"><span>{label}</span><input name={name} type={type} value={value??''} onChange={onChange} required={required} min={min} max={max} step={step} maxLength={maxLength} placeholder={placeholder}/></label>}
export const urgent=(text:string)=>/chest\s*(pain|pressure|tightness)|trouble\s*breathing|can[’']?t\s*breathe|cannot\s*breathe|shortness of breath|suicid|self[- ]?harm|kill\s*myself|end\s*my\s*life|hurt\s*myself|want\s*to\s*die/i.test(text);
export function Emergency(){return <div className="emergency-banner" role="alert"><AlertTriangle size={24}/><div><b>Please get immediate support.</b><p>Chest pain, trouble breathing, or immediate danger: call <a href="tel:911">911</a> in the U.S. For suicidal thoughts or self-harm, call or text <a href="tel:988">988</a>. Outside the U.S., call your local emergency number. Twin cannot assess an emergency.</p><a href="https://www.nimh.nih.gov/health/find-help" target="_blank" rel="noopener noreferrer">Find immediate help ↗</a></div></div>}
export function Chips({sources}:{sources:string[]}){return <div className="source-chips">{sources.map((s,i)=><span key={i}>{s}</span>)}</div>}
