import {useEffect,useRef,useState} from 'react';
import {Heart,Sparkles,FlaskConical,ArrowUpRight,Plus,Pencil,Activity,Sun} from 'lucide-react';
import {toast} from 'sonner';
import {streamChat} from './api';
import {Link,Chips,Emergency,urgent} from './shared';
import {latest,type Message,type ViewProps} from './types';
export default function Twin({s,refresh}:ViewProps){
 const [draft,setDraft]=useState(''),[messages,setMessages]=useState<Message[]>(s.messages),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const log=useRef<HTMLDivElement>(null),controller=useRef<AbortController|null>(null),started=useRef(false),mounted=useRef(true);const p=s.profile;
 useEffect(()=>{if(!busy)setMessages(s.messages)},[s.messages,busy]);
 useEffect(()=>{log.current?.scrollTo(0,log.current.scrollHeight)},[messages]);
 useEffect(()=>()=>{mounted.current=false;controller.current?.abort()},[]);
 const send=async(text:string)=>{
  if(busy||!text.trim())return;setError('');setDraft('');setBusy(true);const input=text.trim();controller.current=new AbortController();
  const uid=crypto.randomUUID(),aid=crypto.randomUUID();
  setMessages(prev=>[...prev,{id:uid,role:'user',content:input,cited_sources:[],mode:'user'},{id:aid,role:'twin',content:'',cited_sources:[],mode:s.aiEnabled?'live':'demo'}]);
  try{await streamChat(input,event=>{if(mounted.current)setMessages(prev=>prev.map(m=>m.id===aid?{...m,content:m.content+(event.delta||''),cited_sources:event.sources??m.cited_sources,mode:event.mode??m.mode}:m));},controller.current.signal);await refresh();}
  catch(e:any){if(e.name!=='AbortError'&&mounted.current){setError(e.message);setDraft(input);toast.error(e.message)}}finally{if(mounted.current)setBusy(false)}
 };
 useEffect(()=>{const prompt=new URLSearchParams(location.search).get('prompt');if(prompt&&!started.current){started.current=true;send(prompt)}},[]);
 const readable=s.connections.some(c=>c.provider==='oura'&&c.status==='connected'&&c.allowed),sleep=latest(s,'sleep_hours');
 const history:Message[]=messages.length?messages:[{id:'welcome',role:'twin',content:`Hey ${p.name}! ${readable&&sleep!==null?`Your latest recorded sleep was ${sleep} hours. `:''}How are you feeling today? We can take a look at the little pieces together.`,cited_sources:readable&&sleep!==null?['Oura · latest recorded sleep']:[],mode:'check-in'}];
 const emergency=urgent(draft)||messages.slice(-2).some(m=>m.role==='user'&&urgent(m.content));
 return <><div className="page-heading"><div><p className="eyebrow">A COMPANION FOR YOUR EVERYDAY</p><h1>A little chat with {p.twin_name} <span className="heading-sun"><Heart size={29}/></span></h1><p>Your health story, in your own words.</p></div><span className={`pill ${s.aiEnabled?'live':''}`}><FlaskConical size={14}/>{s.aiEnabled?'AI connected':'Demo conversation'}</span></div>
 <div className="chat-layout"><section className="chat-paper"><div className="chat-paper-top"><img src={`/art/${p.avatar}.png`} alt="Your avocado twin"/><div><b>{p.twin_name} is here for you</b><span>Small questions are always welcome.</span></div><Sparkles size={23}/></div>{emergency&&<Emergency/>}<div ref={log} className="messages" role="log" aria-live="polite" aria-label="Conversation with your twin">{history.map(m=><article className={`chat-message ${m.role==='user'?'from-user':''}`} key={m.id}>{m.role==='user'?<span className="avatar">{p.name.charAt(0)}</span>:<img className="chat-avatar" src={`/art/${p.avatar}.png`} alt=""/>}<div className="message-content"><span className="message-byline">{m.role==='user'?p.name:p.twin_name}<small>{m.role==='user'?'You':m.mode==='live'?'AI reply':m.mode==='demo'?'Demo reply':'Journal check-in'}</small></span><div className="message-bubble"><p>{m.content||'Thinking about the little pieces…'}</p>{m.role==='twin'&&<Chips sources={m.cited_sources}/>}</div>{m.role==='twin'&&<p className="medical-note">Wellness information, not medical advice.</p>}</div></article>)}</div>
 <div className="prompt-chips">{['How did I sleep this week?','What should I focus on for dinner?','How is my body composition changing?'].map(q=><button key={q} disabled={busy} onClick={()=>send(q)}>{q}<Plus size={13}/></button>)}</div>{error&&<div className="modal-error" role="alert">{error}</div>}<form className="chat-form" onSubmit={e=>{e.preventDefault();send(draft)}}><label className="sr-only" htmlFor="chat-input">Message your twin</label><textarea id="chat-input" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="What’s on your mind?" rows={2} maxLength={4000} required disabled={busy} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(draft)}}}/><button type="submit" className="send-button" aria-label="Send message" disabled={busy||!draft.trim()}><ArrowUpRight size={21}/></button></form><p className="chat-footnote">{s.aiEnabled?'Claude uses only the sources you allow in Privacy. Replies are saved in your journal.':'Demo replies use your saved readings. No health data is sent to an AI service.'}</p></section>
 <aside className="memory-panel"><div className="insights-title"><Heart size={19}/><h2>Little things I know</h2></div><p className="handwritten insights-subtitle">Your story, remembered.</p><div className="memory-card"><span className="eyebrow">YOUR NORTH STAR</span><h3>Feel a little better,<br/>every day.</h3><div className="memory-row">Protein goal <b>{p.protein_goal}g / day</b></div><div className="memory-row">Movement goal <b>{p.move_goal} kcal</b></div><div className="memory-row">Weight goal <b>{p.target_weight} kg</b></div><small>Saved preferences, not clinical targets.</small></div><div className="memory-section"><h3><Heart size={16}/> Your health notes</h3><p>{p.conditions||'No conditions added.'}</p><h3><Activity size={16}/> Medications</h3><p>{p.meds||'No medications added.'}</p><h3><Sun size={16}/> How we check in</h3><p>{{warm:'A warm, encouraging coach',direct:'Clear and straight-talking',clinical:'Calm and factual'}[p.tone]}. Nudges: {p.nudge_freq}.</p></div><Link className="text-button" href="/settings?tab=profile">Edit what I know <Pencil size={14}/></Link><div className="memory-art"><img src="/art/journal.png" alt="An avocado reading beside a sleepy cat"/><p>No perfect days needed.<br/>Just a little curiosity.</p></div></aside></div></>
}
